/* Author: Cristian Gomez - 201801480 */
-- COUNTS de todas las tablas utilizadas 


SELECT COUNT(*) FROM TEMPORARY;
SELECT COUNT(*) FROM SHOP_INVENTORY;
SELECT COUNT(*) FROM INVENTORY;
SELECT COUNT(*) FROM MOVIE_LANGUAGE;
SELECT COUNT(*) FROM LANGUAGE;
SELECT COUNT(*) FROM MOVIE_ACTOR;
SELECT COUNT(*) FROM MOVIE;
SELECT COUNT(*) FROM ACTOR;
SELECT COUNT(*) FROM CATEGORY;
SELECT COUNT(*) FROM RENTAL_MOVIE;
SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM REWARD;
SELECT COUNT(*) FROM EMPLOYEE;
SELECT COUNT(*) FROM SHOP;
SELECT COUNT(*) FROM ADDRESS;
SELECT COUNT(*) FROM CITY;
SELECT COUNT(*) FROM CLASSIFICATION;
SELECT COUNT(*) FROM COUNTRY;


