/* Author: Cristian Gomez - 201801480 */
-- Borrado y creado de la base de datos propuesta */

-- ==================================================================================================
-- Deletion of the entire model
-- ==================================================================================================

DROP TABLE ADDRESS;
DROP TABLE CUSTOMER;
DROP TABLE CITY;
DROP TABLE COUNTRY;

-- ==================================================================================================
-- Creation of the Country table 
-- ==================================================================================================


CREATE TABLE COUNTRY(
    country_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY.
    name            VARCHAR2(200)      NOT NULL,
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

ALTER TABLE COUNTRY 
    ADD CONSTRAINT country_pk PRIMARY KEY(country_id);

-- ==================================================================================================
-- Creation of the city table 
-- ==================================================================================================

CREATE TABLE CITY(
    city_id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name                    VARCHAR(200)    NOT NULL,
    country_id              NUMBER          NOT NULL,
    PRIMARY KEY(city_id),
    FOREIGN KEY(country_id) REFERENCES COUNTRY(country_id)
);

ALTER TABLE CITY
    ADD CONSTRAINT city_pk PRIMARY KEY(city_id);

ALTER TABLE CITY
    ADD CONSTRAINT city_country_fk FOREING KEY(country_id)
        REFERENCES COUNTRY(country_id);


-- ==================================================================================================
-- Creation of the shop table 
-- ==================================================================================================

CREATE TABLE SHOP(
    shop_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    direction       VARCHAR /*PENDIENTE*/
);

ALTER TABLE SHOP 
    ADD CONSTRAINT shop_pk PRIMARY KEY(shop_id);

-- ==================================================================================================
-- Creation of the customer table
-- ==================================================================================================


CREATE TABLE CUSTOMER(
    customer_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name                VARCHAR(200)    NOT NULL,
    surname             VARCHAR(200)    NOT NULL,
    email               VARCHAR(200)    NOT NULL,
    registration_date   DATE            NOT NULL,
    state               VARCHAR2(5)     NOT NULL,
    shop_id             NUMBER          NOT NULL
);

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT customer_pk PRIMARY KEY(customer_id);

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT customer_shop_fk FOREIGN KEY(shop_id)
        REFERENCES SHOP(shop_id);

-- ==================================================================================================
-- Creation of the address table
-- ==================================================================================================


CREATE TABLE ADDRESS(
    address_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    address             VARCHAR(100)    NOT NULL,
    distric             VARCHAR(100)    NOT NULL,
    postal_code         NUMBER(6)       NOT NULL,
    city_id             NUMBER          NOT NULL,
    customer_id         NUMBER          NOT NULL
); 

ALTER TABLE ADDRESS
    ADD CONSTRAINT address_pk PRIMARY KEY(address_id);

ALTER TABLE ADDRESS 
    ADD CONSTRAINT address_city_fk FOREIGN KEY(city_id)
        REFERENCES CITY(city_id);

ALTER TABLE ADDRESS 
    ADD CONSTRAINT address_customer_fk FOREIGN KEY(customer_id)
        REFERENCES CUSTOMER(customer_id);

-- ==================================================================================================
-- Creation of the category table
-- ==================================================================================================


CREATE TABLE CATEGORY(
    category_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name            VARCHAR(100),
);

ALTER TABLE CATEGORY 
    ADD CONSTRAINT category_pk PRIMARY KEY(category_id);

-- ==================================================================================================
-- Creation of the city table 
-- ==================================================================================================

CREATE TABLE ACTOR (
    actor_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name            VARCHAR(200)    NOT NULL,
    surname         VARCHAR(200)    NOT NULL,
);

ALTER TABLE ACTOR 
    ADD CONSTRAINT actor_pk PRIMARY KEY(actor_id);

-- ==================================================================================================
-- Creation of the Movie table 
-- ==================================================================================================

CREATE TABLE MOVIE(
    movie_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title           VARCHAR2(200)   NOT NULL,
    description     VARCHAR2(200)   NOT NULL,
    release_year    NUMBER(4)       NOT NULL,
    duration        TIMESTAMP       NOT NULL,
    days            NUMBER(8)       NOT NULL,
    rental_cost     NUMBER(8,2)     NOT NULL,
    damage_cost     NUMBER(8,2)     NOT NULL,
    classification  VARCHAR2(10)    NOT NULL,
    native_language NUMBER          NOT NULL,
    category_id     NUMBER          NOT NULL
);

ALTER TABLE MOVIE 
    ADD CONSTRAINT movie_pk PRIMARY KEY(movie_id);
ALTER TABLE MOVIE 
    ADD CONSTRAINT movie_category_fk FOREIGN KEY(category_id)
        REFERENCES CATEGORY(category) ON DELETE CASCADE ON UPDATE CASCADE;

-- ==================================================================================================
-- Creation of the language table 
-- ==================================================================================================

CREATE TABLE LANGUAGE(
    language_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name            VARCHAR2(200) NOT NULL
);

ALTER TABLE LANGUAGE 
    ADD CONSTRAINT language_pk PRIMARY KEY(language_id);

-- ==================================================================================================
-- Creation of the Movie_language table 
-- ==================================================================================================


CREATE TABLE MOVIE_LANGUAGE(
    movie_language_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    movie_id                NUMBER      NOT NULL,
    language_id             NUMBER      NOT NULL
);

ALTER TABLE MOVIE_LANGUAGE 
    ADD CONSTRAINT movie_language_pk PRIMARY KEY(movie_language_id);

ALTER TABLE MOVIE_LANGUAGE
    ADD CONSTRAINT movie_language_movie_fk FOREIGN KEY(movie_id)
        REFERENCES MOVIE(movie_id);

ALTER TABLE MOVIE_LANGUAGE
    ADD CONSTRAINT movie_language_language_fk FOREIGN KEY(language_id)
        REFERENCES LANGUAGE(language_id);
